export const GET_POKEMONS = 'GET_POKEMONS'
export const GET_ALL_POKEMONS = 'GET_ALL_POKEMONS'
export const GET_POKEMON_NAME = 'GET_POKEMON_NAME'
export const GET_POKEMON_DETAIL = 'GET_POKEMON_DETAIL'
export const FILTER_TYPE = 'FILTER_TYPE';
export const FILTER_DBAPI = 'FILTER_DBAPI';
export const ORDER_BY_NAME = 'ORDER_BY_NAME';
export const ORDER_BY_ATTACK = 'ORDER_BY_ATTACK';
export const GET_POKEMON_TYPE = 'GET_POKEMON_TYPE';
export const GET_POKEMON_IMG = 'GET_POKEMON_IMG'

